### ISSUE TITLE
Retail sites (kroger, publix, cvs, walgreens, walmart, etc)

### ISSUE THREAD

**Issue by estiens** [usdigitalresponse/vaccine-finder-tools#1]
With the expansion into retail (CVS, Walgreens, Costco, Walmart, Publix, Kroger, etc), there should be a way to make scrapers that are useful across many states - I've started in on Kroger and CVS, but nothing to show yet - keep getting banned from CVS as a bot and still working through mechanizing Kroger's forms.

If there's any interest in centralizing efforts to focus on individual store chains, please let me know!

Bonus: if you work at one of these places and just want to give us an API endpoint and a token, even better!

**Comment by Mr0grog** [comment]
I think it would be great to centralize some of this stuff! Not least because there’s no good reason to slam pharmacies’ sites with lots of people scraping for the same info. If you have a repo where you’re working on this, please feel free to add a PR linking it. (Maybe add a “nationwide” section after “projects by state.”)

**Comment by estiens** [comment]
For sure, if I get any scrapers functional, I'll throw them up and link them!

**Comment by MoralCode** [comment]
> If there's any interest in centralizing efforts to focus on individual store chains, please let me know!

I would definitely be interested in this for [VacFind.org](https://VacFind.org). Currently we are trying to create a [discord server](https://discord.vacfind.org) for volunteers and creators of other COVID-related tools such as this one and i think it would be great to potentially break out some small teams of volunteers to have them focus on maintaining a small scraper for one retailer that can then be part of a larger system to repeatedly scrape and save the data to a national database so there aren't dozens of projects all creating their own scrapers for the same sites
