### ISSUE TITLE
Additional Projects from VacFind List

### ISSUE THREAD

**Issue by MoralCode** [usdigitalresponse/vaccine-finder-tools#4]
Hello! In  working to turn VacFind into a national COVID vaccine availability database, we have come across and saved quite a few links to similar COVID vaccination projects so while I am not a member of any of these projects and cant fill out the information requested, I wanted to contribute a list here in case it is deemed helpful to add them to the list

We are constantly updating our list as well so if you would like to reach out and discuss any of these, feel free to drop me an email at adrian@vacfind.org

- [ ] https://vaccinatenj.com
- [ ] https://vaccinatenm.com
- [ ] ~~https://vaccinateky.com~~ (site appears down)
- [ ] https://vaccinateia.com
- [ ] https://www.vaccinatega.com/
- [ ] https://www.covidwa.com/
- [ ] https://www.vaxxmax.com/
- [ ] https://covid-info.page/dist/#/
- [ ] https://hidrb.com/
- [ ] https://vaccinatepa.org/

**Comment by Mr0grog** [comment]
I think we wound up adding a bunch of these, and others have since shut down. I’m no longer maintaining this list, so I’m closing the issue.
